### ISSUE TITLE
Can't repair broken car

### ISSUE THREAD

**Issue by onscripts** [alberttheprince/popcornrp-customs#27] opened 2024-01-04 07:28 UTC
When you drop a broken car (dead motor) in the polyzone and then you enter the car textUI won't show up.
The only way that it works is that you enter the zone riding the car but how will you do that if the motor is dead???

**Comment by alberttheprince** [comment] 2024-01-05 06:40
This doesn't seem to be an issue with popcornrp-customs, I was able to tow a vehicle into a zone and the textUI showed up. 

Was the vehicle destroyed in a fire or went underwater? In the case of a vehicle being submerged or set on fire there is no way to repair that vehicle.

**Comment by alberttheprince** [comment] 2024-01-06 11:08
I'm closing this issue, if you can provide more proof/evidence related to the issue please open a new issue.

**Comment by alberttheprince** [comment] 2024-08-13 19:19
Reopening this issue, as I was able to reproduce this issue recently - seems the issue is that it only checks on entering and exiting the zone. Would need to check while in a zone as well.

**Comment by Jorn08** [comment] 2024-08-20 16:33
fixed in latest version (v1.4.1)

**Closed as completed by Jorn08** 2024-08-20 16:33 UTC
