### ISSUE TITLE
Wheels Issue

### ISSUE THREAD

**Issue by ItssJxstnDe** [alberttheprince/popcornrp-customs#8] opened 2023-06-05 09:41 UTC
https://youtu.be/-EIetBnNg9Y

I Made this Video to show what is going on.

**Comment by alberttheprince** [comment] 2023-06-12 23:03
Need more information, these look like custom wheels - could be something wrong on your side.  Not sure if your payments are actually going through and it could cancelled because of that.

**Comment by ItssJxstnDe** [comment] 2023-06-13 16:10
Payment goes through and no not custom wheels

**Comment by MsLexey** [comment] 2023-06-28 23:42
After you buy it, don't exit and go to the 'main/other' wheel section and select the same wheel and buy it, then it will work, because from what i've experienced it doesn't save it, only changes the type that you can change the wheels in, technically you're buying the wheel types.

**Comment by alberttheprince** [comment] 2023-11-02 07:07
Can you all let me know if this issue still happens with the most recent update?

**Comment by ShiftyWreckzz** [comment] 2023-11-02 22:25
This is still an issue, seems like the wheel menu is duplicated as well. 

From video preview:
![image](https://github.com/alberttheprince/popcornrp-customs/assets/72171471/03aacb34-2a65-4c87-a560-4d84420c07d3)

Current:
![image](https://github.com/alberttheprince/popcornrp-customs/assets/72171471/205fc0df-6e79-4758-a0f6-9f411ac4892b)

**Comment by Jorn08** [comment] 2023-11-03 22:54
> This is still an issue, seems like the wheel menu is duplicated as well.
> 
> From video preview: ![image](https://user-images.githubusercontent.com/72171471/280142228-03aacb34-2a65-4c87-a560-4d84420c07d3.png)
> 
> Current: ![image](https://user-images.githubusercontent.com/72171471/280142559-205fc0df-6e79-4758-a0f6-9f411ac4892b.png)

Looks like you uncommented the wheels in the config `Config.Mods`

**Comment by Jorn08** [comment] 2023-11-03 22:55
Can't reproduce this issue. Please provide a repro with a freshly spawned car and mention the car type.

**Comment by ShiftyWreckzz** [comment] 2023-11-04 23:56
> Looks like you uncommented the wheels in the config Config.Mods

You are correct after commenting this back out, it saves correctly.

**Comment by alberttheprince** [comment] 2023-11-05 23:50
I assume this is resolved? Closing for now since commenting out the text seems to have fixed it for Shifty. If anyone else still experiences it please open another issue.

**Closed as completed by alberttheprince** 2023-11-05 23:50 UTC
